module.exports = {
    purge: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
    important: true,
    darkMode: false, // or 'media' or 'class'
    theme: {
        extend: {},
    },
    variants: {
        extend: {
            margin: ['last'],
        },
    },
    plugins: [],
    corePlugins: [
        'alignContent',
        'alignItems',
        'alignSelf',
        'backgroundColor',
        'borderColor',
        'borderStyle',
        'borderWidth',
        'cursor',
        'display',
        'flex',
        'flexDirection',
        'flexShrink',
        'flexWrap',
        'fontSize',
        'fontStyle',
        'fontWeight',
        'gap',
        'height',
        'inset',
        'justifyContent',
        'justifyItems',
        'justifySelf',
        'margin',
        'maxHeight',
        'maxWidth',
        'minWidth',
        'outline',
        'overflow',
        'overscrollBehavior',
        'padding',
        'position',
        'resize',
        'rotate',
        'textAlign',
        'textColor',
        'textTransform',
        'transform',
        'transitionDuration',
        'width',
    ]
}
