/* Action Type Constants for ../reducer/configuration */
export const adapterActionTypes = {
    SET_DISCONNECTED: "SET_DISCONNECTED",
    SET_WEB3_CONNECTED: "SET_WEB3_CONNECTED",
    SET_WEB3_ERROR: "SET_WEB3_ERROR",
    SET_WEB3_INFO: "SET_WEB3_INFO",
    SET_WEB3_EPOCH: "SET_WEB3_EPOCH",
    SET_MADNET_CONNECTED: "SET_MADNET_CONNECTED",
    SET_MADNET_ERROR: "SET_MADNET_ERROR",
    SET_MADNET_KEYCHAIN_VALUE: "SET_MADNET_KEYCHAIN_VALUE",
    SET_WEB3_BUSY: "SET_WEB3_BUSY",
    SET_MADNET_BUSY: "SET_MADNET_BUSY",
}