/* Action Type Constants for ../reducer/configuration */
export const adapterActionTypes = {
    SET_DISCONNECTED: "SET_DISCONNECTED",
    SET_WEB3_CONNECTED: "SET_WEB3_CONNECTED",
    SET_WEB3_ERROR: "SET_WEB3_ERROR",
    SET_WEB3_INFO: "SET_WEB3_INFO",
    SET_WEB3_EPOCH: "SET_WEB3_EPOCH",
    SET_ALICENET_CONNECTED: "SET_ALICENET_CONNECTED",
    SET_ALICENET_ERROR: "SET_ALICENET_ERROR",
    SET_ALICENET_KEYCHAIN_VALUE: "SET_ALICENET_KEYCHAIN_VALUE",
    SET_WEB3_BUSY: "SET_WEB3_BUSY",
    SET_ALICENET_BUSY: "SET_ALICENET_BUSY",
};
