/* Action Type Constants for ../reducer/configuration */
export const configActionTypes = {
    TOGGLE_DEFAULT_CURVE: "TOGGLE_DEFAULT_CURVE",
    UPDATE_ETHEREUM_PROVIDER: "UPDATE_ETHEREUM_PROVIDER",
    UPDATE_MAD_NET_CHAIN_ID: "UPDATE_MAD_NET_CHAIN_ID",
    UPDATE_MAD_NET_PROVIDER: "UPDATE_MAD_NET_PROVIDER",
    UPDATE_REGISTRY_CONTRACT_ADDR: "UPDATE_REGISTRY_CONTRACT_ADDR",
}