/* Action Type Constants for ../reducer/interface */
export const middlewareActionTypes = {
    INIT_ALICENET_WALLET: "INIT_ALICENET_WALLET",
    ADD_WALLET_FROM_KEYSTORE: "ADD_WALLET_FROM_KEYSTORE",
    ADD_NEXT_HD_WALLET: "ADD_NEXT_HD_WALLET",
    REINSTANCE_ALICENET_WALLET: "REINSTANCE_ALICENET_WALLET",
    REMOVE_WALLET: "REMOVE_WALLET"
}