/* Action Type Constants for ../reducer/interface */
export const middlewareActionTypes = {
    INIT_MAD_WALLET: "INIT_MAD_WALLET",
    ADD_WALLET_FROM_KEYSTORE: "ADD_WALLET_FROM_KEYSTORE",
    ADD_NEXT_HD_WALLET: "ADD_NEXT_HD_WALLET",
    REINSTANCE_MAD_WALLET: "REINSTANCE_MAD_WALLET",
    REMOVE_WALLET: "REMOVE_WALLET"
}