/* Action Type Constants for ../reducer/modals */
export const modalActionTypes = {
    OPEN_PW_REQUEST: "OPEN_PW_REQUEST",
    CLOSE_PW_REQUEST: "CLOSE_PW_REQUEST",
    OPEN_RENAME_WALLET: "OPEN_RENAME_WALLET",
    CLOSE_RENAME_WALLET: "CLOSE_RENAME_WALLET",
    OPEN_REMOVE_WALLET: "OPEN_REMOVE_WALLET",
    CLOSE_REMOVE_WALLET: "CLOSE_REMOVE_WALLET",
    OPEN_XPORT_PRIVK: "OPEN_XPORT_PRIVK",
    CLOSE_XPORT_PRIVK: "CLOSE_XPORT_PRIVK",
    OPEN_XPORT_KS: "OPEN_XPORT_KS",
    CLOSE_XPORT_KS: "CLOSE_XPORT_KS",
    OPEN_RESET_WALLET: "OPEN_RESET_WALLET",
    CLOSE_RESET_WALLET: "CLOSE_RESET_WALLET"
}