/* Action Type Constants for ../reducer/transaction Actions */
export const transactionActionTypes = {
    CLEAR_LIST: "CLEAR_LIST",
    ADD_TO_LIST: "ADD_TO_LIST",
    REMOVE_FROM_LIST: "REMOVE_FROM_LIST",
    SAVE_CHANGE_RETURN_ADDRESS: "SAVE_CHANGE_RETURN_ADDRESS",
    TOGGLE_STATUS: "TOGGLE_STATUS",
    UPDATE_FROM_LIST: "UPDATE_FROM_LIST",
    SET_LAST_SENT_MINED_TX: "SET_LAST_SENT_MINED_TX",
}