/* Action Type Constants for ../reducer/transaction Actions */
export const transactionActionTypes = {
    SET_PRIORITIZATION_FEE: "SET_PRIORITIZATION_FEE",
    CLEAR_LIST: "CLEAR_LIST",
    ADD_TO_LIST: "ADD_TO_LIST",
    REMOVE_FROM_LIST: "REMOVE_FROM_LIST",
    SAVE_CHANGE_RETURN_ADDRESS: "SAVE_CHANGE_RETURN_ADDRESS",
    TOGGLE_STATUS: "TOGGLE_STATUS",
    UPDATE_FROM_LIST: "UPDATE_FROM_LIST",
    SET_LAST_SENT_MINED_TX: "SET_LAST_SENT_MINED_TX",
    SET_LAST_SENT_TX_HASH: "SET_LAST_SENT_TX_HASH",
    ADD_POLLED_TX: "ADD_POLLED_TX",
    CLEAR_POLLED_TX: "CLEAR_POLLED_TX",
}