/* Action Type Constants for ../reducer/user Actions */
export const userActionTypes = {
    MARK_ACCOUNT_LOCKED: "MARK_ACCOUNT_LOCKED",
    MARK_ACCOUNT_UNLOCKED: "MARK_ACCOUNT_UNLOCKED",
    SET_HAS_VAULT: "SET_HAS_VAULT",
    SET_POTENTIAL_SEED_PHRASE: "SET_POTENTIAL_SEED_PHRASE",
    SET_DESIRED_HD_CURVE: "SET_DESIRED_HD_CURVE",
}