/* Action Type Constants for ../reducer/user Actions */
export const userActionTypes = {
    CLEAR_LOADED_KEYSTORE: "CLEAR_LOADED_KEYSTORE",
    MARK_ACCOUNT_LOCKED: "MARK_ACCOUNT_LOCKED",
    MARK_ACCOUNT_UNLOCKED: "MARK_ACCOUNT_UNLOCKED",
    SET_HAS_VAULT: "SET_HAS_VAULT",
    SET_POTENTIAL_SEED_PHRASE: "SET_POTENTIAL_SEED_PHRASE",
    SET_DESIRED_HD_CURVE: "SET_DESIRED_HD_CURVE",
    SET_KEYSTORE_TO_LOAD: "SET_KEYSTORE_TO_LOAD",
    SET_LOADED_KEYSTORE: "SET_LOADED_KEYSTORE",
}