/* Action Type Constants for ../reducer/modals */
export const vaultActionTypes = {
    SET_WALLETS_STATE: "SET_WALLETS_STATE",
    ADD_INTERNAL_WALLET: "ADD_INTERNAL_WALLET",
    ADD_EXTERNAL_WALLET: "ADD_EXTERNAL_WALLET",
    SET_PREFLIGHT_HASH: "SET_PREFLIGHT_HASH",
    SET_VAULT_TO_STATE: "SET_VAULT_TO_STATE",
}