/* Action Type Constants for ../reducer/modals */
export const vaultActionTypes = {
    ADD_EXTERNAL_WALLET: "ADD_EXTERNAL_WALLET",
    ADD_INTERNAL_WALLET: "ADD_INTERNAL_WALLET",
    MARK_EXISTS_AND_LOCKED: "MARK_EXISTS_AND_LOCKED",
    MARK_EXISTS_AND_UNLOCKED: "MARK_EXISTS_AND_UNLOCKED",
    LOCK_VAULT: "LOCK_VAULT",
    SET_MNEMONIC: "SET_MNEMONIC",
    SET_VAULT_TO_STATE: "SET_VAULT_TO_STATE",
    SET_WALLETS_STATE: "SET_WALLETS_STATE"
}