/* Action Type Constants for ../reducer/modals */
export const vaultActionTypes = {
    ADD_EXTERNAL_WALLET: "ADD_EXTERNAL_WALLET",
    ADD_INTERNAL_WALLET: "ADD_INTERNAL_WALLET",
    MARK_EXISTS_AND_LOCKED: "MARK_EXISTS_AND_LOCKED",
    MARK_EXISTS_AND_UNLOCKED: "MARK_EXISTS_AND_UNLOCKED",
    MARK_OPTOUT__VAULT_NONEXIST_AND_UNLOCKED: "MARK_OPTOUT__VAULT_NONEXIST_AND_UNLOCKED",
    MARK_NONEXIST_NONLOCK_NONOPTOUT: "MARK_NONEXIST_NONLOCK_NONOPTOUT",
    MARK_UNLOCKED: "MARK_UNLOCKED",
    MARK_EXISTS: "MARK_EXISTS",
    LOCK_VAULT: "LOCK_VAULT",
    SET_MNEMONIC: "SET_MNEMONIC",
    SET_VAULT_TO_STATE: "SET_VAULT_TO_STATE",
    SET_WALLETS_STATE: "SET_WALLETS_STATE",
    SET_BALANCES_STATE: "SET_BALANCES_STATE",
    SET_BALANCES_LOADING: "SET_BALANCES_LOADING",
    SET_CURVE: "SET_CURVE",
    UPDATE_RECENT_TXS_BY_ADDRESS: "UPDATE_RECENT_TXS_BY_ADDRESS",
}